version: '3.8'

services:
  web-application:
    build:
      context: ./Web-Application
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - gateway-application

  warehouse-application:
    build:
      context: ./Warehouse-Management-Application
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:warehouse-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - material-application

  material-application:
    build:
      context: ./Material-Management-Application
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:material-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password

  gateway-application:
    build:
      context: ./Gateway-Application
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8085
      - WAREHOUSE_SERVICE_URL=http://warehouse-application:8081
      - MATERIAL_SERVICE_URL=http://material-application:8082
    depends_on:
      - warehouse-application
      - material-application